name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
      - 'LICENSE'
      - 'release.config.js'

env:
  MONKEYTYPE_API_KEY: ${{ secrets.MONKEYTYPE_API_KEY }}

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest]
        include:
          - can-fail: false
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        continue-on-error: ${{ matrix.can-fail }}
      - name: Build package
        run: pnpm build
        continue-on-error: ${{ matrix.can-fail }}
      - name: Eslint - code lint
        run: pnpm lint:es
        continue-on-error: ${{ matrix.can-fail }}
      - name: Prettier - code style
        run: pnpm prettier
        continue-on-error: ${{ matrix.can-fail }}
      - name: Test
        run: pnpm test:ci
        continue-on-error: ${{ matrix.can-fail }}
      - name: Update coverage info for PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: all
          coverage-file: coverage/report.json
          base-coverage-file: coverage/report.json
